title: "Dhruv Gupta"
email: "dhruv.gupta@colorado.edu"
description: "Data Engineer specializing in scalable data systems, analytics, and machine learning."

url: "https://dg291996.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
theme: minimal-mistakes-jekyll

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Theme skin
minimal_mistakes_skin: "mint"

# Author profile settings (REQUIRED for image + sidebar)
author:
  name: "Dhruv Gupta"
  avatar: "/assets/images/profile.jpg"
  bio: "Data Engineer | Machine Learning | Cloud"
  links:
    - label: "GitHub"
      url: "https://github.com/dg291996"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/gupt-a-dhruv"
